### ISSUE TITLE
Composer serve not working

### ISSUE THREAD

**Issue by zhampu** [johannschopplich/aria-kirby-vue-starterkit#1]
`[Sun Apr  5 13:53:54 2020] Failed to listen on 127.0.0.1:8080 (reason: Address already in use)
Script php -S 127.0.0.1:8080 -t public/ cliserver.php handling the serve event returned with error code 1
`
when changing values in composer.json :
`[Sun Apr  5 13:56:15 2020] Failed to listen on 127.0.0.2:8080 (reason: Can't assign requested address)
Script php -S 127.0.0.2:8080 -t public/ cliserver.php handling the serve event returned with error code 1
`

**Comment by johannschopplich** [comment]
Please try any other port than 8080, not another host. The local host has to stay fixed. For example use `127.0.0.1:8082`. 

Which OS are you using? If you have a local webserver like Valet installed and linked to a local URL, you can also paste this address into [env.development](https://github.com/johannschopplich/aria-kirby-vue-starterkit/blob/master/frontend/.env.development).
I use Valet on macOS. Running `valet link` inside the project's root will make the starterkit available locally with `aria-kirby-vue-starterkit.test` (depending on the directory name the command was ran in). I then paste that URL into [env.development](https://github.com/johannschopplich/aria-kirby-vue-starterkit/blob/master/frontend/.env.development) like `VUE_APP_BACKEND_URL=http://aria-kirby-vue-starterkit.test`. 

This is only necessary for development environment. The Vue app has to be connected to the Kirby instance. I hope this helps.

**Comment by zhampu** [comment]
Thanks! using  Valet now too.

so for accessing the panel I should go to http://aria-kirby-vue-starterkit.test/panel and not  http://localhost:8080/panel ?

If yes could you explain a bit further on how to deploy it after `cd frontend && npm run build `?

**Comment by johannschopplich** [comment]
It depends. If you use valet now, the complete Kirby instance is available under http://aria-kirby-vue-starterkit.test, including the panel: http://aria-kirby-vue-starterkit.test/panel

Deploying is fairly simple. You just build the project `cd frontend && npm run build`. This command builds the JS assets. You can then run your site directly via http://aria-kirby-vue-starterkit.test (no need for `npm run serve`, as we have a production environment by then).

On a webserver of your choice, clone your project and run `cd frontend && npm run build`. Point your web server's root to the `public` folder. That's it. 🙂

**Comment by zhampu** [comment]
Thanks for the help!
so if I want to setup this on ftp service such as  godaddy or infomaniak I just need to configure the .htaccess file and direct it to /public right?
example [here](https://www.siteground.com/kb/how_to_change_my_document_root_folder_using_an_htaccess_file/)

**Comment by johannschopplich** [comment]
No, you have to point the web server's root directly to `public`, where the `.htaccess` lies. The file itself is ready to go.
I guess your service provider let's you choose the entry folder of your web application. Usually somehting ending with `/html`.

**Comment by zhampu** [comment]
Got you! yes is online now!
great template!

**Comment by johannschopplich** [comment]
Wonderful to hear! 🙂 If your project shall be visible for the public at any point in time, I would be happy to see it!

**Comment by zhampu** [comment]
hey, I ended up using the other setup: [stationofcommons.org](stationofcommons.org) will do a fork at some moment to credit you :)
so the panel redirects to public/panel and so when I have articles in review they dont show up directly when clicking open to preview them as the slug is adding /public/ to the beginning.

is this something you encountered as well?

**Comment by johannschopplich** [comment]
@zhampu Wow, stunning project! I like the visuals a lot. 🙂 

No, it worked fine for me. I pointed my web server to `/public`, so this directory *is* root. Therefore the panel links work. To do this in an shared environment you'd have to:

Clone your project to `/var/www/zhampu/theproject/`
Then create a symlink `ln -s /var/www/zhampu/theproject/public /var/www/zhampu/stationofcommons.org`

Given that the `example.com` folder is the shared web host's entry point. No if someone accesses `stationofcommons.org`, `/var/www/zhampu/theproject/public/index.php` will be called. Hope my explanation makes sense.

But you don't need the public folder setup. It's just more secure. You can always revert to the standard folder setup. Although it'd be complicated, as all the Vue-related configurations are bound to the public folder setup at the moment.
